# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                    Filter:    3 /    4 =  75.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'utility/configuration'
require 'utility/log'
require 'flexmock'
end

class A
  configuration
  logger
end


class TestConfiguration < Test::Unit::TestCase
  def test_class_instance
    a = A.new
    a.log.info a.options
  end

  def test_options
    a = A.new
    assert('testdb.yaml',a.options['dbfile'])
  end
end



