# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                   Reactor:    6 /    6 = 100.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'network/reactor'
end

class TestReactor < Test::Unit::TestCase
  def setup
    @reactor = Reactor.new(4000, :server, :sockio, [:sga, :echo], [:filter])
  end

  def test_log
    assert_respond_to(@reactor, :log)
  end

  def test_poll
    assert_respond_to(@reactor, :poll)
  end

  def test_register
    assert_respond_to(@reactor, :register)
  end

  def test_start
    assert_respond_to(@reactor, :start)
  end

  def test_stop
    assert_respond_to(@reactor, :stop)
  end

  def test_unregister
    assert_respond_to(@reactor, :unregister)
  end
end

