# Code Generated by ZenTest v. 2.3.0
#                 classname: asrt / meth =  ratio%
#                    Filter:    3 /    4 =  75.00%

unless defined? $ZENTEST and $ZENTEST
require 'test/unit'
require 'utility/log'
require 'flexmock'
end

class A
  logger 'DEBUG'
end

class B < A
  logger 'INFO'
end

class TestLog < Test::Unit::TestCase
  def setup
    a = A.new
    a.log.debug "A debug before B"
    b = B.new
    a.log.debug "A debug after B"
    b.log.debug "B debug not seen"
    b.log.info "B info test"
    a.log.error "A error test"
  end

  def test_class_instance
  end

  def test_loginit
  end
end

