# Code Generated by ZenTest v. 2.4.0
#                 classname: asrt / meth =  ratio%
#                CacheStats:    0 /    3 =   0.00%
#              CacheManager:    0 /   13 =   0.00%
#                CacheEntry:    0 /    9 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestCacheEntry < Test::Unit::TestCase
  def test_clean_bang
    raise NotImplementedError, 'Need to write test_clean_bang'
  end

  def test_dead_eh
    raise NotImplementedError, 'Need to write test_dead_eh'
  end

  def test_dirty_bang
    raise NotImplementedError, 'Need to write test_dirty_bang'
  end

  def test_dirty_eh
    raise NotImplementedError, 'Need to write test_dirty_eh'
  end

  def test_mark_dead
    raise NotImplementedError, 'Need to write test_mark_dead'
  end

  def test_noswap_bang
    raise NotImplementedError, 'Need to write test_noswap_bang'
  end

  def test_noswap_eh
    raise NotImplementedError, 'Need to write test_noswap_eh'
  end

  def test_obj
    raise NotImplementedError, 'Need to write test_obj'
  end

  def test_obj_equals
    raise NotImplementedError, 'Need to write test_obj_equals'
  end

  def test_oid
    raise NotImplementedError, 'Need to write test_oid'
  end

  def test_oid_equals
    raise NotImplementedError, 'Need to write test_oid_equals'
  end

  def test_swap_bang
    raise NotImplementedError, 'Need to write test_swap_bang'
  end
end

class TestCacheManager < Test::Unit::TestCase
  def test_delete
    raise NotImplementedError, 'Need to write test_delete'
  end

  def test_get
    raise NotImplementedError, 'Need to write test_get'
  end

  def test_keys
    raise NotImplementedError, 'Need to write test_keys'
  end

  def test_log
    raise NotImplementedError, 'Need to write test_log'
  end

  def test_makenoswap
    raise NotImplementedError, 'Need to write test_makenoswap'
  end

  def test_makeswap
    raise NotImplementedError, 'Need to write test_makeswap'
  end

  def test_mark
    raise NotImplementedError, 'Need to write test_mark'
  end

  def test_options
    raise NotImplementedError, 'Need to write test_options'
  end

  def test_put
    raise NotImplementedError, 'Need to write test_put'
  end

  def test_stats
    raise NotImplementedError, 'Need to write test_stats'
  end

  def test_sync
    raise NotImplementedError, 'Need to write test_sync'
  end

  def test_sync_chain
    raise NotImplementedError, 'Need to write test_sync_chain'
  end
end

class TestCacheStats < Test::Unit::TestCase
  def test_each
    raise NotImplementedError, 'Need to write test_each'
  end

  def test_inc
    raise NotImplementedError, 'Need to write test_inc'
  end
end

# Number of errors detected: 3
